extern const GeoLayout bits_area_1_geo[];
extern const GeoLayout bits_area_1[];
extern const Collision bits_area_1_collision[];
extern const MacroObject bits_area_1_macro_objs[];
extern Lights1 bits_dl_Cloud_lights;
extern u8 bits_dl_SUPER_MARIO_64_51D4DA7F_0_2_all_i8[];
extern Vtx bits_dl_Platform_mesh_layer_1_vtx_0[448];
extern Gfx bits_dl_Platform_mesh_layer_1_tri_0[];
extern Gfx mat_bits_dl_Cloud[];
extern Gfx bits_dl_Platform_mesh_layer_1[];
extern Gfx bits_dl_material_revert_render_settings[];
