extern const GeoLayout ice_platform_broken_geo[];
extern Lights1 ice_platform_broken_IceBroken_lights;
extern u8 ice_platform_broken_ice_broken_ci8[];
extern u8 ice_platform_broken_ice_broken_ci8_pal_rgba16[];
extern Vtx ice_platform_broken_Cube_mesh_layer_1_vtx_0[24];
extern Gfx ice_platform_broken_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_ice_platform_broken_IceBroken[];
extern Gfx mat_revert_ice_platform_broken_IceBroken[];
extern Gfx ice_platform_broken_Cube_mesh_layer_1[];
extern Gfx ice_platform_broken_material_revert_render_settings[];
